# .github/workflows/deploy.yml
name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ] # Trigger the workflow on push to the main branch
  workflow_dispatch: # Allow manual triggering

# Permissions are not needed for Firebase deployment
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js, pnpm, and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm' # This tells setup-node to use pnpm for caching

      - name: Install dependencies, build, and deploy
        run: |
          pnpm install
          pnpm run build
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          # No GITHUB_ACTIONS needed, but Firebase secrets are still required for the build
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
